---QUESTION 1
SELECT *
FROM Data_property24;

---QUESTION 2
SELECT CITY,PROVINCE,PROPERTY_PRICE 
FROM Data_property24;

---QUESTION 3
SELECT DISTINCT PROVINCE 
FROM Data_property24;

---QUESTION 4 
SELECT*
FROM Data_property24
WHERE PROVINCE= 'Gauteng';

---QUESTION 5
SELECT*
FROM Data_property24
WHERE PROPERTY_PRICE>1500000;

---QUESTION 6
SELECT*
FROM Data_property24
WHERE BEDROOMS>3;

---QUESTION 7
SELECT*
FROM Data_property24
WHERE PARKING>=2;

---QUESTION 8
SELECT*
FROM Data_property24
WHERE Monthly_Repayment>25000;

---QUESTION 9
SELECT*
FROM Data_property24
ORDER BY PROPERTY_PRICE DESC;

---QUESTION 10 
SELECT*
FROM Data_property24
ORDER BY FLOOR_SIZE ASC;

---QUESTION 11
SELECT*
FROM Data_property24
WHERE PROVINCE='Gauteng'
ORDER BY Monthly_Repayment;

---QUESTION 12
SELECT*
FROM Data_property24
WHERE PROVINCE= 'Western Cape' AND PROPERTY_PRICE<3000000;

---QUESTION 13
SELECT*
FROM Data_property24
WHERE PROVINCE = 'KwaZulu-Natal' AND BEDROOMS>=3;

---QUESTION 14
SELECT*
FROM Data_property24
WHERE PROVINCE IN ('Limpopo', 'Free State')
ORDER BY PROPERTY_PRICE;

---QUESTION 15
SELECT TOP 10 *
FROM Data_property24
ORDER BY PROPERTY_PRICE DESC;

---QUESTION 16
SELECT TOP 5 *
FROM Data_property24
ORDER BY PROPERTY_PRICE ASC;

---QUESTION 17
SELECT TOP 10 *
FROM Data_property24
ORDER BY FLOOR_SIZE DESC;

---QUESTION 18
SELECT TOP 1 PROVINCE
FROM Data_property24
ORDER  BY (PROPERTY_PRICE) DESC;

---QUESTION 19
SELECT  TOP 25 CITY
FROM Data_property24
ORDER  BY (PROPERTY_PRICE) ASC;

---QUESTION 20
SELECT TOP 1 Min_Gross_Monthly_Income 
FROM Data_property24
WHERE PROPERTY_PRICE>4000000;



